# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DEMO' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DEMO
pod 'Modelable', :path=>'../'
  target 'DEMOTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Modelable', :path=>'../'
  end

  target 'DEMOUITests' do
pod 'Modelable', :path=>'../'
    # Pods for testing
  end

end
